name: cy_app
description: A new Flutter application.


publish_to: 'none'

version: 0.1.3+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: 3.0.10
  flustars: ^0.3.2
  flutter_swiper: ^1.1.6
  font_awesome_flutter: ^8.4.0
  image_picker: ^0.6.7+17
  qr_flutter: ^3.1.0
  shared_preferences: ^0.5.2
  fluttertoast: ^3.1.0
  modal_progress_hud: ^0.1.3
  package_info: ^0.4.0+3
  device_info: ^1.0.0
  photo_view: ^0.4.2
  video_player: ^0.10.1
  chewie: ^0.9.7
  flutter_downloader: ^1.1.7
  path_provider: ^1.1.0
  flutter_webview_plugin: ^0.3.5
  permission_handler: ^3.1.0
  flutter_local_notifications: ^0.7.1+1
  flutter_inappbrowser: ^1.2.1
  provider: ^3.0.0+1
  rxdart: ^0.22.0
  flutter_luban: ^0.1.7+1
  intl: ^0.15.8
  sqflite: ^1.1.6
  flutter_easyrefresh: ^2.1.8
  flutter_cache_manager: ^1.0.0
  cached_network_image: ^1.0.0
  carousel_slider: ^2.3.1
  flutter_tag_layout: ^0.0.3
  url_launcher: ^5.7.10

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/image/invite-bg.png
    - assets/splash.png
    - assets/splash.jpg
    - assets/banner_00.png
    - assets/banner_01.png
    - assets/banner_02.png
    - assets/v0.png
    - assets/v1.png
    - assets/v2.png
    - assets/v3.png
    - assets/v4.png
    - assets/v5.png
